# Zookeeper配置文件
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/opt/data/zookeeper
clientPort=2181
maxClientCnxns=0
admin.enableServer=false
autopurge.snapRetainCount=3
autopurge.purgeInterval=24
4lw.commands.whitelist=*

# 集群配置
server.1=centos-201:2888:3888
server.2=centos-202:2888:3888
server.3=centos-203:2888:3888