# 命名Agent的组件
agent.sources = tail-source
agent.channels = kafka-channel



# 使用更可靠的TAILDIR Source（推荐）
agent.sources.tail-source.type = TAILDIR
agent.sources.tail-source.filegroups = f1
agent.sources.tail-source.filegroups.f1 = /opt/module/applog/log/app.*
agent.sources.tail-source.positionFile = /opt/module/flume/taildir_position.json

# 配置Channel
agent.channels.kafka-channel.type = org.apache.flume.channel.kafka.KafkaChannel
agent.channels.kafka-channel.bootstrap.servers = centos-101:9092,centos-103:9092
agent.channels.kafka-channel.topic = topic_log
agent.channels.kafka-channel.parseAsFlumeEvent = false


agent.sources.tail-source.channels = kafka-channel