agent.sources = exec-source
agent.channels = memory-channel
agent.sinks = logger-sink

agent.sources.exec-source.type = exec
agent.sources.exec-source.command = tail -F /opt/module/applog/log/app_test.log
agent.sources.exec-source.channels = memory-channel

agent.channels.memory-channel.type = memory
agent.channels.memory-channel.capacity = 1000

agent.sinks.logger-sink.type = logger
agent.sinks.logger-sink.channel = memory-channel
