# 命名Agent的组件
agent.sources = tail-source
agent.channels = mem-channel
agent.sinks = kafka-sink


# 使用更可靠的TAILDIR Source（推荐）
agent.sources.tail-source.type = TAILDIR
agent.sources.tail-source.filegroups = f1
agent.sources.tail-source.filegroups.f1 = /opt/module/applog/log/app.*
agent.sources.tail-source.positionFile = /opt/module/flume/taildir_position.json

# 配置Channel
#

agent.channels.mem-channel.type = memory
agent.channels.mem-channel.capacity = 10000
agent.channels.mem-channel.transactionCapacity = 1000
agent.sources.tail-source.channels = mem-channel

# ======================
# # Sink：KafkaSink（必须）
# # ======================
agent.sinks.kafka-sink.type = org.apache.flume.sink.kafka.KafkaSink
agent.sinks.kafka-sink.channel = mem-channel
agent.sinks.kafka-sink.kafka.bootstrap.servers = centos-201:9092,centos-203:9092
agent.sinks.kafka-sink.kafka.topic = topic_log
agent.sinks.kafka-sink.kafka.producer.acks = 1
