a1.sources = r1
a1.channels = c1
a1.sinks = k1

#配置source为kafkasource
a1.sources.r1.type = org.apache.flume.source.kafka.KafkaSource
a1.sources.r1.channels = c1
a1.sources.r1.kafka.bootstrap.servers = centos-101:9092,centos-102:9092,centos-103:9092
a1.sources.r1.kafka.topics = topic_log
#指定消费者组ID,防止多个Flume实例消费重复数据,重要的是,当多个Flume实例消费同一个topic时,消费者组ID必须不同
#保证每个 Flume agent 的 group.id 唯一
# 避免与旧 consumer 冲突
a1.sources.r1.kafka.group.id = flume_topic_log_group
#a1.sources.r1.interceptors = i1
#a1.sources.r1.interceptors.i1.type = org.example.flume.interceptor.JsonValidateInterceptor$Builder

#配置channel
a1.channels.c1.type = file
a1.channels.c1.checkpointDir = /opt/module/flume/checkpoint/behavior1
a1.channels.c1.dataDirs = /opt/module/flume/data/behavior1
a1.channels.c1.capacity = 1000000
a1.channels.c1.keepAlive = 10
a1.channels.c1.maxFileSize = 102400000

#配置sink为hdfs
a1.sinks.k1.type = hdfs
a1.sinks.k1.hdfs.path = hdfs://centos-101:8020/original_data/gmall/log/topic_log/%Y-%m-%d
a1.sinks.k1.hdfs.filePrefix = log
a1.sinks.k1.hdfs.round = false

a1.sinks.k1.hdfs.rollInterval = 10
a1.sinks.k1.hdfs.rollSize = 128000000
a1.sinks.k1.hdfs.rollCount = 0
#控制输出文件类型
a1.sinks.k1.hdfs.fileType = CompressedStream
a1.sinks.k1.hdfs.codeC = gzip

a1.sinks.k1.channel = c1



